### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by quentinus95** [p-project/p-seeder-cli#2]
Unmet peer dependency while installing the app:

![image](https://user-images.githubusercontent.com/8060564/28362486-daa76208-6c7c-11e7-865c-0374f7d3a802.png)

**Comment by IGI-111** [comment]
I can't reproduce this on a clean install whether through the deployer or by itself.

**Comment by quentinus95** [comment]
This is strange as I was experiencing this on both Ubuntu and now Arch. Does webpack needs to be installed globally?

**Comment by IGI-111** [comment]
Scratch that, it does warn me on the second run of `npm install`, but not the first. Weird.

We should probably just add it as a dependency.
